# Generated by Django 4.2 on 2023-04-19 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Addresses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regione', models.CharField(max_length=100)),
                ('ville', models.CharField(max_length=100)),
                ('quartie', models.CharField(max_length=100)),
                ('code_postal', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomRestaurant', models.CharField(max_length=100)),
                ('adresseRestaurant', models.CharField(max_length=100)),
                ('typeCuisine', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomUtilisateur', models.CharField(max_length=100)),
                ('prenomUtilisateur', models.CharField(max_length=100)),
                ('adresseUtilisateur', models.CharField(max_length=100)),
                ('emailUtilisateur', models.CharField(max_length=100)),
                ('motDePass', models.CharField(max_length=100)),
                ('telephoneUtilisateur', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='NoteRestaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(max_length=100)),
                ('commentaire', models.TextField()),
                ('idRestaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RestaurantApplication.restaurant')),
                ('idUtilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RestaurantApplication.utilisateur')),
            ],
        ),
    ]
